apiVersion: v1
kind: Service
metadata:
  labels:
    app: ducta11-kubernetes-udagram-api-feed
  name: ducta11-kubernetes-udagram-api-feed-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/ducta11-kubernetes-udagram-api-feed-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ducta11-kubernetes-udagram-api-feed
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
